status = [
    "Build (macOS-latest, nightly)",
    "Build (ubuntu-latest, nightly)",
    "Cargo tests (macOS-latest, nightly)",
    "Cargo tests (ubuntu-latest, nightly)",
    "Clippy",
    "Format check (ubuntu-latest, nightly)",
    "KVM Tests",
    "Rusty-Hermit Kernel based integration tests",
    "Rusty-Hermit Kernel Tests",
]
delete_merged_branches = true
timeout_sec = 7200
