status = [
    "Check (ubuntu-latest)",
    "Check (macos-latest)",
    "Test (ubuntu-latest)",
    "Test (macos-latest)",
    "Integration Tests",
    "rusty_demo",
    "Format",
    "Clippy (ubuntu-latest)",
    "Clippy (macos-latest)",
    "Coverage",
]
delete_merged_branches = true
timeout_sec = 7200
