status = [
    "Build (macos-latest)",
    "Build (ubuntu-latest)",
    "Cargo tests (macos-latest)",
    "Cargo tests (ubuntu-latest)",
    "Clippy",
    "Format",
    "KVM Tests",
    "Rusty-Hermit Kernel based integration tests",
    "Rusty-Hermit Kernel Tests",
]
delete_merged_branches = true
timeout_sec = 7200
