name: CI

on:
  push:
    branches:
      - master
      - staging
      - trying
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - run: cargo check --all-targets

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cargo test --lib -- --skip test_vm
          cargo test --bins --examples
          cargo test --doc

  integration-tests:
    name: Integration Tests
    runs-on: [self-hosted]
    steps:
      - name: Install gdb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdb
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout benches_data/hello_world
      - name: Integration Tests
        run: cargo test --lib --test '*'

  rusty_demo:
    name: rusty_demo
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          path: uhyve
      - uses: actions/checkout@v2
        with:
          repository: hermitcore/rusty-hermit
          path: rusty-hermit
          submodules: true
      - name: Build rusty_demo
        run: cargo build -p rusty_demo
        working-directory: rusty-hermit
      - name: Run rusty_demo
        run: RUST_LOG=debug cargo run -- --verbose ../rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
        working-directory: uhyve
      - name: Run rusty_demo
        run: RUST_LOG=debug cargo run --release -- --verbose ../rusty-hermit/target/x86_64-unknown-hermit/debug/rusty_demo
        working-directory: uhyve

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: cargo fmt --all -- --check
      - name: Format Test Kernels
        run: cargo fmt --all -- --check
        working-directory: tests/test-kernels

  clippy:
    name: Clippy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
      - name: Install rusty-hermit dependencies
        run: cargo install cargo-download cargo-binutils
      - name: Clippy Test Kernels
        run: cargo clippy --all-targets -- -D warnings
        working-directory: tests/test-kernels
      
  coverage:
    name: Coverage
    runs-on: [self-hosted]
    steps:
      - name: Install gdb
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdb
      - uses: actions/checkout@v2
        with:
          lfs: true
      - run: git lfs checkout benches_data/hello_world
      - name: Install cargo-llvm-cov
        run: curl -LsSf https://github.com/taiki-e/cargo-llvm-cov/releases/latest/download/cargo-llvm-cov-x86_64-unknown-linux-gnu.tar.gz | tar xzf - -C ~/.cargo/bin
      - name: Generate code coverage
        run: cargo llvm-cov --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: lcov.info
          fail_ci_if_error: true
