name: KVM Tests

on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying

jobs:
  kvm:
    runs-on: [self-hosted]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with: 
         rust-version: nightly
         components: 'rustfmt, clippy'
         targets: 'x86_64-unknown-linux-gnu'
    - uses: actions/checkout@v2.3.4
      with:
         submodules: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Build (debug)
      run:
         cargo build
    - name: Build (release)
      run:
         cargo build --release
